### ISSUE TITLE
no such file or directory - monaco-editor / package.json

### ISSUE THREAD

**Issue by hassandraga** [alifcommunity/alif-editor#1]
**Error:**
`Error writing to cache: ENOENT: no such file or directory, stat 'Z:\Hassan\Codes\alif-editor\node_modules\monaco-editor\package.json'`

**Comment by waseeld** [comment]
Is the problem still there??
Can you put more details??

**Comment by assawalhy** [comment]
يبدو أنك لم تصطب الاعتماديات 

```
yarn
```
