### ISSUE TITLE
 codemirror@v6 | تداخل الألوان

### ISSUE THREAD

**Issue by me00001** [alifcommunity/alif-editor#2]
<div dir="rtl">
السلام عليكم, التلوين جذاب والمحرر ذاته مناسب للغة :1st_place_medal: 

لاحظت هذا الخطأ في كلمة **نصوص** 

وكان لابد من التبليغ :smiley: 
</div>

![لقطة شاشة من 2021-06-26 05-53-22](https://user-images.githubusercontent.com/37930867/123500088-17c77580-d644-11eb-89b8-7db36e82d344.png)

**Comment by assawalhy** [comment]
<div dir=rtl>

وعليكم السلام ورحمة الله وبركاته 👋! شكرا للتبليغ، سأعمل على هذا إن شاء الله

</div>

**Comment by assawalhy** [comment]
تم حل المشكلة، أرجو التجربة على موقع المحرر (لا حاجة للتجربة محليا)
